title: WebSRD
description: Everything you need to play 5E
theme: just-the-docs
color_scheme: custom-light

url: https://just-the-docs.github.io

aux_links:
  View WebSRD on Github: https://github.com/akcode2/5eDocs
