title: WebSRD
description: Everything you need to play 5E
theme: just-the-docs
color_scheme: custom-light

url: https://ash-cache.github.io/5eDocs

aux_links:
  View WebSRD on Github: https://github.com/ash-cache/5eDocs
