title: 5E Docs
description: 5E SRD on the web
theme: just-the-docs
color_scheme: custom-light

url: https://just-the-docs.github.io

aux_links:
  View 5E Docs on Github: https://github.com/akcode2/5eDocs
